/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Builder;

import Business.EcoSystem;
import Business.UserAccountManagement.UserAccount;
import Business.WorkQueue.ListingRequest;
import Business.WorkQueue.ListingRequestDirectory;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manoj Chandrasekaran
 */
public class BuilderRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmaOrder
     */
    private UserAccount userAcc;
    private EcoSystem system;
    private JPanel container;

    public BuilderRequestsJPanel(EcoSystem system, JPanel userProcessContainer, UserAccount userAcc) {
        initComponents();
        this.system = system;
        this.container = userProcessContainer;
        this.userAcc = userAcc;
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listingsTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        costTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listingTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        updateStatus = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        jPanel1.setBackground(new java.awt.Color(250, 249, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        listingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student Name", "Consultant name", "Order Status"
            }
        ));
        listingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listingsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listingsTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 780, 310));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        costTextArea.setColumns(20);
        costTextArea.setRows(5);
        costTextArea.setBorder(null);
        jScrollPane3.setViewportView(costTextArea);

        jLabel2.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        jLabel2.setText("Cost");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 360, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        listingTextArea.setColumns(20);
        listingTextArea.setRows(5);
        listingTextArea.setBorder(null);
        jScrollPane2.setViewportView(listingTextArea);

        jLabel1.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        jLabel1.setText("Listing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 360, 190));

        updateStatus.setBackground(new java.awt.Color(51, 51, 255));
        updateStatus.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        updateStatus.setForeground(new java.awt.Color(255, 255, 255));
        updateStatus.setText("Update status");
        updateStatus.setBorder(null);
        updateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusActionPerformed(evt);
            }
        });
        jPanel1.add(updateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 200, 39));

        resetButton.setBackground(new java.awt.Color(255, 55, 95));
        resetButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setBorder(null);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, 180, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusActionPerformed
        // TODO add your handling code here:
        UpdateStatus();
    }//GEN-LAST:event_updateStatusActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
       resetOrder();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void listingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingsTableMouseClicked
        // TODO add your handling code here:

        displayRequest();
    }//GEN-LAST:event_listingsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea costTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea listingTextArea;
    private javax.swing.JTable listingsTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton updateStatus;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        // System.out.print("im inside display table "+system);
//        Req_MedicineDir reMedDir = system.getMedicineReqDir();
//        ArrayList<Req_Medicine> medorderList = reMedDir.getMedReqDir();
//
//        int l = medorderList.size();
//        Pharma ph = (Pharma) userAcc;
//        for (int i = 0; i < l; i++) {
//            Req_Medicine medReq = medorderList.get(i);
//            if (ph.getPharmaName().matches(medReq.getPharmaName())) {
//                DefaultTableModel table = (DefaultTableModel) listingsTable.getModel();
//                String r1 = String.valueOf(medReq.getId());
//
//                String r2[] = {r1, medReq.getPatientId(), medReq.getDoctorName(), medReq.getStatus()};
//                table.addRow(r2);
//
//            }
//        }

    }

    private void UpdateStatus() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel table = (DefaultTableModel) listingsTable.getModel();
        int selectedRow = listingsTable.getSelectedRow();
        if (selectedRow >= 0) {
            int sRow = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());

//            Req_MedicineDir medReqDir = system.getMedicineReqDir();
//            ArrayList<Req_Medicine> medOrderList = medReqDir.getMedReqDir();
//
//            int l = medOrderList.size();
//
//            for (int i = 0; i < l; i++) {
//                Req_Medicine medReq = medOrderList.get(i);
//                if (sRow == medReq.getId()) {
//                    if (medReq.getStatus().matches("Order Placed")) {
//                        medReq.setStatus("Ready for pickup");
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Order Cancelled");
//
//                    }
//                }
//            }
//            listingsTable.setModel(new DefaultTableModel(null, new String[]{"ID", "Patient Name", "Doctor Name", "Status"}));
            displayTable();
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }

    }

    private void displayRequest() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        costTextArea.setText("");
        listingTextArea.setText("");

        DefaultTableModel table = (DefaultTableModel) listingsTable.getModel();
        int selectedRow = listingsTable.getSelectedRow();
        int sRow = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());

        ListingRequestDirectory directory = system.getListingRequestDirectory();
        List<ListingRequest> listings = directory.getListingRequirement();

        int listSize = listings.size();
        for (int i = 0; i < listSize; i++) {
            ListingRequest listingRequest = listings.get(i);
            if (sRow == listingRequest.getId()) {
                Map<String, String> f = listingRequest.getListingOrderList();
                int count = 1;
                for (String key : f.keySet()) {
                    listingTextArea.append("Item " + count + " : " + key + " Quantity : " + f.get(key) + "\n");
                    count++;

                }
//                Map<String, String> medCostmap = medReq.getMedCostlist();
//                int num = 0;
//                for (String key : medCostmap.keySet()) {
//
//                    num = num + (Integer.parseInt(medCostmap.get(key)));
//
//                }
//                costTextArea.append(String.valueOf(num));

            }
        }

    }

    private void resetOrder() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  
     DefaultTableModel table = (DefaultTableModel) listingsTable.getModel();
        int selectedRow = listingsTable.getSelectedRow();
        if (selectedRow >= 0) {
            int sRow = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());

//            Req_MedicineDir medReqDir = system.getMedicineReqDir();
//            ArrayList<Req_Medicine> medorderList = medReqDir.getMedReqDir();
//
//            int l = medorderList.size();
//
//            for (int i = 0; i < l; i++) {
//                Req_Medicine medreq = medorderList.get(i);
//                if (sRow == medreq.getId()) {
//                    if (medreq.getStatus().matches("Ready for pickup")) {
//                        medreq.setStatus("Order Placed");
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Order Cancelled");
//
//                    }
//                }
//            }
            listingsTable.setModel(new DefaultTableModel(null, new String[]{"ID", "Patient Name", "Doctor Name", "Status"}));
            displayTable();
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }
    
    
    }
}
