/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HousingDevelopmentBoard;

import Business.EcoSystem;
import Business.UserAccountManagement.UserAccount;
import Business.HouseDevelopmentBoard.Questionnaire;
import Business.HouseDevelopmentBoard.QuestionnaireDirectory;
import Utility.PieChart;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author nagarjunmallesh
 */
public class Statistics extends javax.swing.JPanel {

    
    private UserAccount userAcc;
    private EcoSystem system;
//    private JPanel container;
    /**
     * Creates new form Statistics
     * @param userAcc
     * @param ecosystem
     */    
    public Statistics( UserAccount userAcc,EcoSystem ecosystem) {
        initComponents();
        this.system = ecosystem;
        this.userAcc = userAcc;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentalStats = new javax.swing.JButton();
        universityStats = new javax.swing.JButton();
        preferredStats = new javax.swing.JButton();
        houseStats = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1110, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentalStats.setBackground(new java.awt.Color(51, 51, 255));
        rentalStats.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        rentalStats.setForeground(new java.awt.Color(255, 255, 255));
        rentalStats.setText("Rental Statistics");
        rentalStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalStatsActionPerformed(evt);
            }
        });
        add(rentalStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 310, 140));

        universityStats.setBackground(new java.awt.Color(51, 51, 255));
        universityStats.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        universityStats.setForeground(new java.awt.Color(255, 255, 255));
        universityStats.setText("University Statistics");
        universityStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityStatsActionPerformed(evt);
            }
        });
        add(universityStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 310, 140));

        preferredStats.setBackground(new java.awt.Color(51, 51, 255));
        preferredStats.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        preferredStats.setForeground(new java.awt.Color(255, 255, 255));
        preferredStats.setText("Preferred Stores");
        preferredStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferredStatsActionPerformed(evt);
            }
        });
        add(preferredStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 310, 140));

        houseStats.setBackground(new java.awt.Color(51, 51, 255));
        houseStats.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        houseStats.setForeground(new java.awt.Color(255, 255, 255));
        houseStats.setText("Preffered House types");
        houseStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseStatsActionPerformed(evt);
            }
        });
        add(houseStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 310, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void rentalStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalStatsActionPerformed
        // TODO add your handling code here:
        try {
              QuestionnaireDirectory questionnaireDir = system.getQuestionnaireDirectory();
              List<Questionnaire> questionnaire = questionnaireDir.getQuestionnaireDirectory();
            

            int rangeWithinThousand=0;
            int rangeWithinTwoThousand=0;
            int rangeWithinFourThousand=0;
            int rangeBeyondFourThousand=0;
            
            for(int i=0;i<questionnaire.size();i++)
            {

                Questionnaire c2 = questionnaire.get(i);
                if(c2.getExpectedRent().matches("500 - 1000"))
                {
                    rangeWithinThousand += 1;
                }else  if(c2.getExpectedRent().matches("1000 - 2000"))
                {
                    rangeWithinTwoThousand += 1;
                }else  if(c2.getExpectedRent().matches("2000 - 4000"))
                {
                    rangeWithinFourThousand += 1;
                }else  if(c2.getExpectedRent().matches("4000+"))
                {
                    rangeBeyondFourThousand += 1;
                }
            }
            rangeWithinThousand = (rangeWithinThousand + 1) * 100000;
            rangeWithinTwoThousand = (rangeWithinTwoThousand + 1) * 100000;
            rangeWithinFourThousand = (rangeWithinFourThousand + 1) * 100000;
            rangeBeyondFourThousand = (rangeBeyondFourThousand + 1) * 100000;
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Rent Range $500-$1000", rangeWithinThousand);
            pieDataset.setValue("Rent Range $1000-$2000", rangeWithinTwoThousand);
            pieDataset.setValue("Rent Range $2000-$4000", rangeWithinFourThousand);
            pieDataset.setValue("Rent Range $4000+", rangeBeyondFourThousand);

            PieChart pieChart = new PieChart("Rent Range Statistics",pieDataset);
            ChartPanel test = pieChart.getChartPanel();
            JFrame frame = new JFrame();
            frame.add(test);
            frame.pack();
            frame.setVisible(true);
            
        } catch(Exception ex) {
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_rentalStatsActionPerformed

    private void universityStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityStatsActionPerformed
        // TODO add your handling code here:
     try {
              QuestionnaireDirectory questionnaireDir = system.getQuestionnaireDirectory();
              List<Questionnaire> questionnaire = questionnaireDir.getQuestionnaireDirectory();
            

            int northeastern=0;
            int mit=0;
            int harvard=0;
            int bostonUni=0;
            
            for(int i=0;i<questionnaire.size();i++)
            {

                Questionnaire c2 = questionnaire.get(i);
                if(c2.getAdmittedUniversity().matches("Northeastern"))
                {
                    northeastern += 1;
                }else  if(c2.getAdmittedUniversity().matches("MIT"))
                {
                    mit += 1;
                }else  if(c2.getAdmittedUniversity().matches("Harvard"))
                {
                    harvard += 1;
                }else  if(c2.getAdmittedUniversity().matches("BU"))
                {
                    bostonUni += 1;
                }
            }
            northeastern = (northeastern + 1) * 100000;
            mit = (mit + 1) * 100000;
            harvard = (harvard + 1) * 100000;
            bostonUni = (bostonUni + 1) * 100000;
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Northeastern University", northeastern);
            pieDataset.setValue("MIT", mit);
            pieDataset.setValue("Harvard", harvard);
            pieDataset.setValue("Boston University", bostonUni);

            PieChart pieChart = new PieChart("University Statistics",pieDataset);
            ChartPanel test = pieChart.getChartPanel();
            JFrame frame = new JFrame();
            frame.add(test);
            frame.pack();
            frame.setVisible(true);
            
        } catch(Exception ex) {
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_universityStatsActionPerformed

    private void preferredStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferredStatsActionPerformed
        // TODO add your handling code here:
        try {
              QuestionnaireDirectory questionnaireDir = system.getQuestionnaireDirectory();
              List<Questionnaire> questionnaire = questionnaireDir.getQuestionnaireDirectory();
            

            int target=0;
            int walmart=0;
            int stopAndShop=0;
            int patelBrothers=0;
            
            for(int i=0;i<questionnaire.size();i++)
            {

                Questionnaire c2 = questionnaire.get(i);
                if(c2.getConvenienceStore().matches("Target"))
                {
                    target += 1;
                }else  if(c2.getConvenienceStore().matches("Walmart"))
                {
                    walmart += 1;
                }else  if(c2.getConvenienceStore().matches("Stop & Shop"))
                {
                    stopAndShop += 1;
                }else  if(c2.getConvenienceStore().matches("Patel Brothers"))
                {
                    patelBrothers += 1;
                }
            }
            target = (target + 1) * 100000;
            walmart = (walmart + 1) * 100000;
            stopAndShop = (stopAndShop + 1) * 100000;
            patelBrothers = (patelBrothers + 1) * 100000;
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Target", target);
            pieDataset.setValue("Walmart", walmart);
            pieDataset.setValue("Stop & Shop", stopAndShop);
            pieDataset.setValue("Patel Brothers", patelBrothers);

            PieChart pieChart = new PieChart("Convenience Store Statistics",pieDataset);
            ChartPanel test = pieChart.getChartPanel();
            JFrame frame = new JFrame();
            frame.add(test);
            frame.pack();
            frame.setVisible(true);
            
        } catch(Exception ex) {
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_preferredStatsActionPerformed

    private void houseStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseStatsActionPerformed
        // TODO add your handling code here:
                try {
              QuestionnaireDirectory questionnaireDir = system.getQuestionnaireDirectory();
              List<Questionnaire> questionnaire = questionnaireDir.getQuestionnaireDirectory();
            

            int studio=0;
            int apartment=0;
            int independentHouse=0;
            int shared=0;
            
            for(int i=0;i<questionnaire.size();i++)
            {

                Questionnaire c2 = questionnaire.get(i);
                if(c2.getHousingType().matches("Studio"))
                {
                    studio += 1;
                }else  if(c2.getHousingType().matches("Apartment"))
                {
                    apartment += 1;
                }else  if(c2.getHousingType().matches("Independent House"))
                {
                    independentHouse += 1;
                }else  if(c2.getHousingType().matches("Shared"))
                {
                    shared += 1;
                }
            }
            studio = (studio + 1) * 100000;
            apartment = (apartment + 1) * 100000;
            independentHouse = (independentHouse + 1) * 100000;
            shared = (shared + 1) * 100000;
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            pieDataset.setValue("Studio Apartment", studio);
            pieDataset.setValue("Apartment", apartment);
            pieDataset.setValue("Independent House", independentHouse);
            pieDataset.setValue("Shared Accomodations", shared);

            PieChart pieChart = new PieChart("Housing Type Statistics",pieDataset);
            ChartPanel test = pieChart.getChartPanel();
            JFrame frame = new JFrame();
            frame.add(test);
            frame.pack();
            frame.setVisible(true);
            
        } catch(Exception ex) {
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_houseStatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton houseStats;
    private javax.swing.JButton preferredStats;
    private javax.swing.JButton rentalStats;
    private javax.swing.JButton universityStats;
    // End of variables declaration//GEN-END:variables
}
